name: SimpleATM
main: Runesmacher.SimpleATM.SimpleATM
version: 1.1
author: Runesmacher
description: SimpleATM is an add-on for iConomy which lets you interact with your in hand balance at the click of an ATM-sign.