name: SimpleATM
main: Runesmacher.SimpleATM.SimpleATM
version: 2.1
author: Runesmacher
description: SimpleATM is an add-on for all major bukkit Economies which lets you interact with your in hand balance at the click of an ATM-sign.